# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
   
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }} 
         
    - run: npm install 
      working-directory: .\frontend  
    - run: npm ci
      working-directory: .\frontend 
    - run: npm run build --if-present
      working-directory: .\frontend   
    - name: NPM-Version
  # You may pin to the exact commit or the version.
  # uses: Reedyuk/NPM-Version@805800379b213c9193ede2c7a7f14a1a99e4d10b
      uses: Reedyuk/NPM-Version@1.2.1
      with:
    # This will be the version you want to set in the package.json file
        version: 9.8.1
    # The location of the package.json file, defaults to current directory.
        package: ./frontend   
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven    
      run: |
           mvn -B -DskipTests package --file pom.xml
           mkdir staging && cp D:\a\fullstack\fullstack\backend\target\*.jar staging
    - name: Docker Build Tag Publish
  # You may pin to the exact commit or the version.
  # uses: bitovi/github-actions-docker-publish@def3cb9a3ef842b230bf575dc4f5e280ae6a6896
      uses: bitovi/github-actions-docker-publish@v1.0.7
      with:
    # Checkout the repository
    # checkout: # optional, default is true
    # Tag to override default Logic
    #image_tag: # optional, default is 
    # Use the SHA for the tag.  Overrides the default logic.
     #  use_sha: # optional, default is false
    # Docker org name.
    #org_name: # optional, default is 
    # Name of the docker repository
       repo_name: fullstackapp
    # Tag default branch with latest tag instead of branch name.
    #use_latest: # optional, default is true
    # Docker user
       docker_username: hocinemab
    # Docker password
       docker_password: Allahoakbar1982/
    # Add a string of values to the end of the build command
    #  build_args: # optional
    # Specify the working directory that the docker build will be run in
   #  working-directory:
         
    - name: register workflow data as artifact
      uses: actions/upload-artifact@v2
      with: 
         name: github-actions-artifact
         path: staging
    - name: Maven Cache
      # You may pin to the exact commit or the version.
      # uses: skjolber/maven-cache-github-action@b1d76adcd43ba2e253cb04c5dbe67d0ea599f65b
      uses: skjolber/maven-cache-github-action@v2.0
      with:
    # Build step step, i.e. restore or save
         step: restore
     
      
      
    
    
